site_name: projeto ETL - Workshop
theme: 
  name: material # or other theme
  palette:
    primary: blue
  language: pt

repo_name: "mmcrispim/workshop_estrut"
repo_url: "https://github.com/mmcrispim/workshop_estrut"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python